<div class="box-window-6">
    <?php echo $this->formEdit->titulo ?>
    <form id="form" action="<?php echo APP_PATH . '/usuarios/save/' ?>" method="post">
        <div class="form-row">
            <?php echo $this->formEdit->id ?>

            <div class="form-group col-md-12">
                <div class="form-group col-md-12">
                    <?php echo $this->formEdit->nome ?>
                </div>
                <div class="form-group col-md-12">
                    <?php echo $this->formEdit->email ?>
                </div>
                <div class="form-group col-md-12">
                    <?php echo $this->formEdit->senha ?>
                </div>
                <div class="form-group col-md-12">
                    <?php echo $this->formEdit->senha_confirma ?>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formEdit->btnSalvar ?>
                <a href="<?php echo APP_PATH . '/usuarios/' ?>"><?php echo $this->formEdit->btnFechar ?></a>
            </div>
        </div>
    </form>
</div>

<script>
    $("#form").submit(function () {

        if ($("input[name='senha']").val() != $("input[name='senha_confirma']").val()){
            alert('Senhas diferentes');
            return false;
        }
    })

</script>