<div class="box-window">

    <?php $saldoAcumulado = 0?>
    <?php foreach ($this->dadosConta as $key => $conta): ?>


      <?php  $this->calcSaldo($conta['id']);?>

        <h6 style="background-color: #ecf0f1;width: 100%;height: 30px;padding:5px;font-size: small"><b>Conta - <?php echo $conta['conta'] ?></b></h6>
        <table id="tabela" class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col" style="width: 3%">id</th>
                <th scope="col" style="width: 10%"><?php echo $this->translate("Data") ?></th>

                <th scope="col" style="width: 30%"><?php echo $this->translate("Descricao") ?></th>

                <th scope="col" style="width: 5%"><?php echo $this->translate("Tipo") ?></th>
                <th scope="col" style="width: 10%;text-align: right"><?php echo $this->translate("Valor") ?></th>
                <th scope="col" style="width: 10%;text-align: right"><?php echo $this->translate("Saldo") ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $lancamentos = $this->lancamentosTable->listLancamentos(array(
                "where" => "conta_id = {$conta['id']}",
                "order" => "data_lancamento,id asc"
            )); ?>

            <?php foreach ($lancamentos as $dados) : ?>



            <?php ($dados['saldo'] < 0) ? $styleSaldo = "style='color:red;text-align: right'" : $styleSaldo = "style='color:black;text-align: right'" ?>
            <?php ($dados['valor'] < 0) ? $styleValor = "style='color:red;text-align: right'" : $styleValor = "style='color:black;text-align: right'" ?>


            <tr class="linha" id="<?php echo $dados['id'] ?>">
                <td><?php echo $dados['id'] ?></td>
                <td><?php echo DateService::DateEngToBr($dados['data_lancamento']) ?></td>

                <td><?php echo $dados['descricao'] ?></td>

                <td><?php echo $dados['tipo'] ?></td>

                <td <?php echo $styleValor ?>><?php echo NumberService::toMoney($dados['valor'],2,null,true) ?></td>
                <td <?php echo $styleSaldo ?>><?php echo NumberService::toMoney($dados['saldo'],2,null,true) ?></td>

                <?php endforeach; ?>
            </tbody>
        </table>
        <?php  $saldoAcumulado = $saldoAcumulado + $dados['saldo']?>
        <h6 style="background-color: lemonchiffon;width: 100%;height: 30px;padding:5px;font-size: small;text-align: right"><b>Saldo <?php echo NumberService::toMoney($dados['saldo'],2,null,true)    ?></b></h6>

    <?php endforeach; ?>
    <h6 style="background-color: khaki;width: 100%;height: 30px;padding:5px;font-size: small;text-align: right"><b>Saldo Acumulado <?php echo NumberService::toMoney($saldoAcumulado,2,null,true)    ?></b></h6>
    <?php echo $this->formList->pagination ?>
</div>


<?php $this->parts("list-modal-options"); ?>

<script>
    $(document).ready(function () {
        $('.linha').click(function () {

            $(document).ready(function () {
                $('.linha').click(function () {

                    var id = this.id;


                    $('#edit').attr({
                        href: "<?php echo APP_PATH . '/lancamentos/edit/?id=' ?>" + id
                    })
                    $('#delete').attr({
                        href: "<?php echo APP_PATH . '/lancamentos/delete/?id=' ?>" + id
                    })
                    $("#btn-modal").click();

                })
            })
        })
    })
</script>

