<div class="box-window">
    <?php echo $this->formCreate->titulo ?>
    <form action="<?php echo APP_PATH . '/lancamentos/save/' ?>" method="post">
        <div class="form-row">
            <?php echo $this->formCreate->id ?>
            <div class="form-group col-md-12">
                <?php echo $this->formCreate->centro_custo_id ?>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3">
                <?php echo $this->formCreate->data_lancamento ?>
            </div>
            <div class="form-group col-md-3">
                <?php echo $this->formCreate->conta_id ?>
            </div>
            <div class="form-group col-md-3">
                <?php echo $this->formCreate->tipo ?>
            </div>
            <div class="form-group col-md-3">
                <?php echo $this->formCreate->valor ?>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formCreate->descricao ?>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formCreate->fluxo_id ?>
            </div>
        </div>


        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formCreate->btnSalvar ?>
                <a href="<?php echo APP_PATH . '/lancamentos/' ?>"><?php echo $this->formCreate->btnFechar ?></a>
            </div>
        </div>
    </form>
</div>



