<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">My Money 1.0</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Cadastros
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/usuarios/'?>"><?php echo $this->translate("Usuarios") ?></a>
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/entidades/'?>"><?php echo $this->translate("Entidades") ?></a>
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/centro-custo/'?>"><?php echo $this->translate("Centros Custos") ?></a>
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/bancos/'?>"><?php echo $this->translate("Bancos") ?></a>
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/contas/'?>"><?php echo $this->translate("Contas") ?></a>
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/fluxos/'?>"><?php echo $this->translate("Fluxos Conta") ?></a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Financeiro
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                    <a class="dropdown-item" href="<?php echo APP_PATH.'/lancamentos/'?>"><?php echo $this->translate("Lancamentos") ?></a>

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Relatorios
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="<?php echo APP_PATH.'/contas/relatorios/contas'?>"><?php echo $this->translate("Contas") ?></a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sobre</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sair</a>
            </li>

        </ul>
    </div>
</nav>
