<div class="box-window">
    <?php echo $this->formCreate->titulo ?>
    <form action="<?php echo APP_PATH . '/contas/save/' ?>" method="post">
        <div class="form-row">
            <?php echo $this->formCreate->id ?>
            <div class="form-group col-md-6">
                <?php echo $this->formCreate->banco_id ?>
            </div>
            <div class="form-group col-md-6">
                <?php echo $this->formCreate->tipo ?>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <?php echo $this->formCreate->agencia ?>
            </div>
            <div class="form-group col-md-6">
                <?php echo $this->formCreate->conta ?>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formCreate->btnSalvar ?>
                <a href="<?php echo APP_PATH . '/contas/' ?>"><?php echo $this->formCreate->btnFechar ?></a>
            </div>
        </div>
    </form>
</div>