<div class="box-window-6">
    <?php echo $this->formLogin->titulo ?>
    <form id="form" action="<?php echo APP_PATH . '/usuarios/auth/' ?>" method="post">
        <div class="form-row">


            <div class="form-group col-md-12">

                <div class="form-group col-md-12">
                    <?php echo $this->formLogin->email ?>
                </div>
                <div class="form-group col-md-12">
                    <?php echo $this->formLogin->senha ?>
                </div>

            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <?php echo $this->formLogin->btnEntrar ?>
                <a href="<?php echo APP_PATH . '/usuarios/login/' ?>"><?php echo $this->formLogin->btnSair ?></a>
            </div>
        </div>
    </form>
</div>

<script>
   /* $("#form").submit(function () {

        if ($("input[name='senha']").val() != $("input[name='senha_confirma']").val()){
            alert('Senhas diferentes');
            return false;
        }

    })*/

</script>